name: 'Runs RubyCritic checks for your project'
description: 'Runs RubyCritic checks for your project'
author: 'ptuchster'
inputs:
  workdir:
    description: "The directory from which to look for and run RubyCritic. Default '.'"
    default: '.'
  use_bundler:
    description: "Run RubyCritic with bundle exec. Default: `false`"
    default: 'false'
  min_score_treshold:
    description: "Minimal score threshold to be passed at pipeline. Default: `90`"
    default: '90'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/main.sh
      shell: sh
      env:
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_USE_BUNDLER: ${{ inputs.use_bundler }}
        INPUT_MIN_SCORE_THRESHOLD: ${{ inputs.min_score_treshold }}
branding:
  icon: 'check-circle'
  color: 'red'
